---
kind: Service
apiVersion: v1
metadata:
  name: "{{ template "logstash.fullname" . }}-headless"
  labels:
    app: "{{ template "logstash.fullname" . }}"
    chart: "{{ .Chart.Name }}"
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
{{- if .Values.labels }}
{{ toYaml .Values.labels | indent 4 }}
{{- end }}
spec:
 type: NodePort
 selector:
 app: logstash
 ports:
 — name: http
 port: {{ .Values.httpPort }}
 nodePort: 31123
 — name: tcp
 port: 9500 
 nodePort: 30123
